on:
  push:
    tags:
      - "v*"
      - "latest"

name: Pre-release

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(pre-release): automated change"
          branch: master
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            target/release/switcher 
      - uses: katyo/publish-crates@v1
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
